Repository DevDavido/performance-audit-plugin, pull requests merged in 2023-12, with the labels that each got.

#41 Translations update from Hosted Weblate
  lang/az.json
  lang/bn.json
  lang/de.json
  lang/dv.json
  lang/el.json
  lang/eo.json
  lang/es.json
  lang/eu.json
  lang/gu.json
  lang/hy.json
  lang/ja.json
  lang/ku.json
  lang/lb.json
  lang/ms.json
  lang/nb.json
  lang/nl.json
  lang/pt-br.json
  lang/pt.json
  lang/si.json
  lang/sv.json
  lang/tr.json
  lang/tzm.json
  lang/uk.json
  lang/zh-tw.json
Labels: L10n

#49 Enable automated Dependabot updates
  .github/dependabot.yml
  composer.json
Labels: enhancement, dependabot

#51 feat: Search for Node executable additionally in paths of PATH environment variable
  CHANGELOG.md
  Exceptions/DependencyMissingException.php
  ExecutableFinder.php
  plugin.json
Labels: enhancement, node-related
